services:
  web:
    #image: mondedie/flarum:stable
    build:
      context: .
    env_file:
      - flarum.env
    volumes:
      # - ./assets:/flarum/app/assets
      - ./assets:/flarum/app/public/assets
      - ./extensions:/flarum/app/extensions
      - ./storage/logs:/flarum/app/storage/logs
      - ./nginx:/etc/nginx/flarum
    ports:
      - 8888:8888
    depends_on:
      - db

  db:
    image: mariadb:10.5
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxxxxxxx
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=xxxxxxxxxx
    volumes:
      - ./db:/var/lib/mysql
